### ISSUE TITLE
Screenshots cropped when using docker image

### ISSUE THREAD

**Issue by montanaflynn** [chromedp/docker-headless-shell#5]
I'm using chromedp to take a full page screenshot and it works great when running on my mac but inside docker the screenshot is the correct dimensions but the image is cropped at the size of the window:

```go
package main

import (
	"context"
	"io/ioutil"
	"log"

	"github.com/chromedp/cdproto/emulation"
	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"
)

func main() {

	url := "https://html.com/document/"

	// create context
	ctx, cancel := chromedp.NewContext(context.Background())
	defer cancel()

	// run task list
	var imageBytes []byte
	err := chromedp.Run(ctx, chromedp.Tasks{
		emulation.SetDeviceMetricsOverride(int64(1024), int64(4000), 1.0, false),
		chromedp.Navigate(url),
		chromedp.WaitVisible("container", chromedp.ByID),
		chromedp.ActionFunc(func(ctx context.Context) error {
			_, _, contentRect, err := page.GetLayoutMetrics().Do(ctx)
			if err != nil {
				return err
			}

			v := page.Viewport{
				X:      contentRect.X,
				Y:      contentRect.Y,
				Width:  contentRect.Width,
				Height: contentRect.Height,
				Scale:  1,
			}
			buf, err := page.
				CaptureScreenshot().
				WithFormat(page.CaptureScreenshotFormatJpeg).
				WithQuality(90).
				WithClip(&v).
				Do(ctx)
			if err != nil {
				return err
			}
			imageBytes = buf
			return nil
		}),
	})
	if err != nil {
		log.Fatal(err)
	}

	// save the screenshot to disk
	if err = ioutil.WriteFile("./screenshots/screenshot.png", imageBytes, 0644); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by mvdan** [comment]
Most likely, this issue should be on the chromedp repo and not here. Unless you have a specific reason to believe that the docker image is to blame?

**Comment by montanaflynn** [comment]
@mvdan chromepd seems to work fine until it's ran in the docker image

**Comment by mvdan** [comment]
What about if you use headless-shell outside a docker image? Perhaps it's the binary that matters.

Still, I very much doubt this image and repo are to blame; this just builds headless-shell into a tiny image.

**Comment by montanaflynn** [comment]
@mvdan I'm not sure how to use headless-shell outside a docker image. 

I added the full program above, when ran on my mac using chromedp I get a full screenshot but when running in this docker image I get a cropped screenshot so it seems the problem is with headless-shell or running chromedp in docker.

**Comment by mvdan** [comment]
Ok. I still think this issue belongs in the main repo, unless you can prove that the Dockerfile or build script are to blame. Issues in this repo are likely to not get noticed, anyway.

**Comment by mvdan** [comment]
Closing - feel free to reopen this issue in the main chromedp issue tracker.
